-- Update products with correct data from the application
TRUNCATE public.products RESTART IDENTITY;

INSERT INTO public.products (id, name, brand, description, price, image, category, featured, in_stock, rating, reviews, fragrance, size) VALUES
(1, 'Ethereal Bloom', 'Scent Trail', 'A captivating blend of delicate florals with subtle woody undertones. This enchanting fragrance opens with fresh bergamot and lily of the valley, transitioning to a heart of rose and jasmine, before settling into a warm base of sandalwood and amber.', 9600, '/perfume1.jpg', 'floral', true, true, 4.8, 124, '{"topNotes": ["Bergamot", "Lily of the Valley"], "middleNotes": ["Rose", "Jasmine"], "baseNotes": ["Sandalwood", "Amber"]}', '{"value": 50, "unit": "ml"}'),
(2, 'Midnight Velvet', 'Scent Trail', 'An intoxicating oriental fragrance that captivates with its rich and mysterious character. Beginning with spicy black pepper and cardamom, it unfolds into a heart of sensual vanilla and exotic oud, finally revealing a lasting impression of musk and patchouli.', 10800, '/perfume2.jpg', 'oriental', true, true, 4.7, 98, '{"topNotes": ["Black Pepper", "Cardamom"], "middleNotes": ["Vanilla", "Oud"], "baseNotes": ["Musk", "Patchouli"]}', '{"value": 50, "unit": "ml"}'),
(3, 'Citrus Awakening', 'Scent Trail', 'A refreshing and invigorating blend that brings to life the essence of sun-drenched citrus groves. Sparkling notes of lemon and grapefruit create an energizing opening, followed by aromatic rosemary and mint heart notes, finishing with a light cedar and vetiver base.', 7600, '/perfume3.jpg', 'citrus', false, true, 4.5, 76, '{"topNotes": ["Lemon", "Grapefruit"], "middleNotes": ["Rosemary", "Mint"], "baseNotes": ["Cedar", "Vetiver"]}', '{"value": 50, "unit": "ml"}'),
(4, 'Ocean Breeze', 'Scent Trail', 'A fresh aquatic fragrance that captures the essence of a coastal retreat. This invigorating scent opens with sea salt and cucumber, develops into a heart of lavender and marine notes, and settles into a clean base of white musk and ambergris.', 8800, '/perfume4.jpg', 'fresh', true, true, 4.6, 103, '{"topNotes": ["Sea Salt", "Cucumber"], "middleNotes": ["Lavender", "Marine Notes"], "baseNotes": ["White Musk", "Ambergris"]}', '{"value": 50, "unit": "ml"}'),
(5, 'Spiced Teakwood', 'Scent Trail', 'A sophisticated woody fragrance with warm spice accents. The composition begins with cinnamon and nutmeg, transitions to a heart of rich teakwood and cedarwood, and lingers with comforting notes of tonka bean and vanilla.', 10000, '/perfume5.jpg', 'woody', false, false, 4.9, 87, '{"topNotes": ["Cinnamon", "Nutmeg"], "middleNotes": ["Teakwood", "Cedarwood"], "baseNotes": ["Tonka Bean", "Vanilla"]}', '{"value": 50, "unit": "ml"}'),
(6, 'Golden Nectar', 'Scent Trail', 'A luxurious gourmand fragrance that entices with its sweet sophistication. Opening with honey and almond, it evolves to reveal praline and caramel heart notes, finally settling into a rich base of vanilla and chocolate.', 11200, '/perfume6.jpg', 'gourmand', false, true, 4.7, 92, '{"topNotes": ["Honey", "Almond"], "middleNotes": ["Praline", "Caramel"], "baseNotes": ["Vanilla", "Chocolate"]}', '{"value": 50, "unit": "ml"}');

SELECT setval('products_id_seq', 6);