// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://athtckywzwdslgitvwij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0aHRja3l3endkc2xnaXR2d2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzM2NzQsImV4cCI6MjA2MjEwOTY3NH0.9WU-6V--MCK21tqj9MMesXyLO_GzTZR3QOrcVX89-eg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);